### PR TITLE
Checked that account exists

### PR DESCRIPTION
**Pull request by RogerNoble**
Seems the account endpoint doesn't always return all the accounts. Added
a check to see it exists before attempting to get the `displayName`.

### CODE REVIEW

**Comment by RogerNoble** [comment]
@RobertoGraham I see. Do you happen to know the endpoint for `getExternalAuths` so I can add the implementation?

**Comment by RobertoGraham** [comment]
The external auth objects are included in accounts returned by `Endpoint.displayNameFromIds`

```
[ {
  "id" : "4035ca150e3a447a8f95680d19ce0f7c",
  "displayName" : "Morrissh24",
  "externalAuths" : {
    "psn" : {
      "type" : "psn",
      "externalAuthId" : "7225186713796739299",
      "accountId" : "4035ca150e3a447a8f95680d19ce0f7c",
      "externalDisplayName" : "Morrissh24"
    }
  }
} ]
```

**Comment by qlaffont** [comment]
@RogerNoble did you finish your pull request ? Can i merge ?

**Comment by RogerNoble** [comment]
@qlaffont Feel free if you are happy with the fix.

I have not had a chance to implement the suggestion from @RobertoGraham.  However I usually prefer to keep PR's small so probably best addressed separately.

**Pull request merged**
