### PR TITLE
[WIP] Add Profile / Challenge Lookup for the logged in user.

### PR DESCRIPTION
**Pull request by ericlewis**
This adds profile / challenge lookup for the logged in user, the quest data is incomplete, but most of is there. Will need to update for each week. Staged challenges aren't returned if you haven't completed them it seems, so I am missing some mappings. Haven't tested with an account that doesn't have battle pass. Please give it a test, feel free to help add quest info.

### CODE REVIEW

**Comment by qlaffont** [comment]
Tell me when you have finished to developed your feature and i will test it ;)

**Comment by ericlewis** [comment]
It’s done enough to test! I would love to find out what quests are missing.

**Comment by qlaffont** [comment]
I will test it this week end ;)

**Comment by ericlewis** [comment]
Closing this because my branch has diverged quite a lot

**Comment by qlaffont** [comment]
Okay np.

**Pull request closed without merging**
