### PR TITLE
Suppress console logging with debug option.

### PR DESCRIPTION
**Pull request by AlcaDesign**

### CODE REVIEW

**Comment by qlaffont** [comment]
Nice code tested ?

**Comment by AlcaDesign** [comment]
As far as I know, this code should _now_ be stable and acceptable.

```javascript
> new Fortnite();
Error: Please give credentials [Email, Password, Client Launcher Token, Client Fortnite Token]
    at new FortniteApi (D:\node\Alcabot\node_modules\fortnite-api\index.js:18:13)
```
```javascript
> new Fortnite([]);
Error: Please give credentials [Email, Password, Client Launcher Token, Client Fortnite Token]
    at new FortniteApi (D:\node\Alcabot\node_modules\fortnite-api\index.js:18:13)
```
```javascript
> new Fortnite(['','','','']);
FortniteApi { debug: false, credentials: [ '', '', '', '' ] }
```
```javascript
> new Fortnite([], {});
Error: Please give credentials [Email, Password, Client Launcher Token, Client Fortnite Token]
    at new FortniteApi (D:\node\Alcabot\node_modules\fortnite-api\index.js:18:13)
```
```javascript
> new Fortnite([], { debug: true });
Fortnite-API - Please give credentials [Email, Password, Client Launcher Token, Client Fortnite Token]
Error: Please give credentials [Email, Password, Client Launcher Token, Client Fortnite Token]
    at new FortniteApi (D:\node\Alcabot\node_modules\fortnite-api\index.js:18:13)
```
```javascript
> new Fortnite(['','','',''], { debug: true });
Fortnite-API - Credentials Params OK
FortniteApi { debug: true, credentials: [ '', '', '', '' ] }
```

**Comment by qlaffont** [comment]
I will check it on the end of the week

**Comment by qlaffont** [comment]
Validated.

**Pull request merged**
